removed image for test and deploy

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -116,26 +116,32 @@ test:
     - pwd
     - ls -la
     - cargo test --verbose
-
 # Generate Documentation
 document:
   stage: document
   script:
-    - echo "Generating documentation with cargo doc"
-    - cargo doc --no-deps
-    - ARTIFACTS_DIR_RELATIVE="${ARTIFACTS_DIR}/doc"  # Relative path for artifacts
-    - echo "Checking if target/doc exists"
-    - ls -la target/doc
-    - echo "Ensuring ${ARTIFACTS_DIR_RELATIVE} exists"
-    - mkdir -p ${ARTIFACTS_DIR_RELATIVE}
-    - echo "Moving generated docs to ${ARTIFACTS_DIR_RELATIVE}"
-    - mv target/doc/* ${ARTIFACTS_DIR_RELATIVE}/
-    - echo "Listing contents of ${ARTIFACTS_DIR_RELATIVE}"
+    - echo "Generating documentation with cargo doc..."
+    - cargo doc --no-deps || { echo "cargo doc failed"; exit 1; }
+
+    - ARTIFACTS_DIR_RELATIVE="${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/doc"
+    - echo "Checking if target/doc exists..."
+    - if [ -d "target/doc" ]; then
+      echo "target/doc directory found. Proceeding with moving files..."
+      mkdir -p ${ARTIFACTS_DIR_RELATIVE} || { echo "Failed to create artifacts directory"; exit 1; }
+      mv target/doc/* ${ARTIFACTS_DIR_RELATIVE}/ || { echo "Failed to move documentation files"; exit 1; }
+      echo "Documentation files moved to ${ARTIFACTS_DIR_RELATIVE}"
+      else
+      echo "target/doc directory not found. Documentation generation failed."
+      exit 1
+      fi
+
+    - echo "Listing contents of ${ARTIFACTS_DIR_RELATIVE}..."
     - ls -la ${ARTIFACTS_DIR_RELATIVE}
   artifacts:
     paths:
-      - ${ARTIFACTS_DIR_RELATIVE}  # Use relative path here
+      - ${ARTIFACTS_DIR_RELATIVE}
     expire_in: 1 week
+
 
 
 deploy:
